name: ${CONTAINER_NAME}

services:
    ##############################################################################
    # Terminal
    ##############################################################################
    terminal:
        image: ${TERMINAL_IMAGE_NAME}
        profiles: ["term"]
        container_name: ${CONTAINER_NAME}-env-terminal
        command: ["zsh"]
        stdin_open: true
        tty: true
        working_dir: "/project"
        volumes:
            - ../../:/project
            - ../.cache/terminal/.zsh_history:/root/.zsh_history
            - ../.cache/terminal/.bash_history:/root/.bash_history
            - ../.cache/terminal/.npm/_cacache:/root/.npm/_cacache
            - ../.cache/terminal/.npm/_logs:/root/.npm/_logs
            - ../.cache/terminal/.composer/cache:/root/.composer/cache
            - ../.cache/terminal/.composer/auth.json:/root/.composer/auth.json
